"""
Seed the artists table with an initial curated set.

Run once after deploying the schema:
  cd the-roster/pipeline && python seed.py

No Spotify API credentials needed — artist names are hardcoded.
image_url and genre are left null; the scraper fills them in on first run.
"""
from db import get_client

SEED_ARTISTS = [
    # ── Global superstars (will be classified 'major' — not signable) ────────
    {"spotify_id": "06HL4z0CvFAxyc27GXpf02", "name": "Taylor Swift"},
    {"spotify_id": "3TVXtAsR1Inumwj472S9r4", "name": "Drake"},
    {"spotify_id": "1Xyo4u8uXC1ZmMpatF05PJ", "name": "The Weeknd"},
    {"spotify_id": "4q3ewBCX7sLwd24euuV69X", "name": "Bad Bunny"},
    {"spotify_id": "6eUKZXaKkcviH0Ku9w2n3V", "name": "Ed Sheeran"},
    {"spotify_id": "1uNFoZAHBGtllmzznpCI3s", "name": "Justin Bieber"},
    {"spotify_id": "66CXWjxzNUsdJxJ2JdwvnR", "name": "Ariana Grande"},
    {"spotify_id": "246dkjvS1zLTtiykXe5h60", "name": "Post Malone"},
    {"spotify_id": "0Y5tJX1MQlPlqiwlOH1tJY", "name": "Travis Scott"},
    {"spotify_id": "2YZyLoL8N0Wb9xBt1NhZWg", "name": "Kendrick Lamar"},
    {"spotify_id": "7tYKF4w9nC0nq9CsPZTHyP", "name": "SZA"},
    {"spotify_id": "790FomKkXshlbRYZFtlgla", "name": "Karol G"},
    {"spotify_id": "6qqNVTkY8uBg9cP3Jd7DAH", "name": "Billie Eilish"},
    {"spotify_id": "3Nrfpe0tUJi4K4DXYWgMUX", "name": "BTS"},
    {"spotify_id": "2h93pZq0e7k5yf4dywlkpM", "name": "Olivia Rodrigo"},
    {"spotify_id": "6KImCVD70vtIoJWnq6nGn3", "name": "Harry Styles"},
    {"spotify_id": "4MCBfE4596Uoi2O4DtmEMz", "name": "Juice WRLD"},
    {"spotify_id": "1McMsnEElThX1knmY4oliG", "name": "Ozuna"},
    {"spotify_id": "0oSGxfWSnnOXhD2fKuz2Gy", "name": "David Bowie"},
    {"spotify_id": "4tZwfgrHOc3mvqYlEYSvVi", "name": "Daft Punk"},
    {"spotify_id": "6l3HvQ5sa6mXTsMTB19rO5", "name": "J. Cole"},
    {"spotify_id": "3Y7RZ31TRPVadSFVy1o8os", "name": "H.E.R."},
    # ── French / Francophone artists ──────────────────────────────────────────
    {"spotify_id": "7IlRNXHjoOCgEAWN5qYksg", "name": "Aya Nakamura"},
    {"spotify_id": "0GOx72r5AAEKRGQFn3xqXK", "name": "GIMS"},
    {"spotify_id": "1rHOtdmGNr5vcYNw5v7QGC", "name": "Kenny Beats"},
    {"spotify_id": "3IW7ScrzXmPvZhB27hmfgy", "name": "Jul"},
    {"spotify_id": "6Te49r3A6f5BiIgBRxH7FH", "name": "Ninho"},
    {"spotify_id": "6W5uA6CNMf3hd2j4a2XWCx", "name": "Naps"},
    {"spotify_id": "7gU9VyFRN3JWPJ5oHOil60", "name": "Tayc"},
    {"spotify_id": "4sbXXFzEWJY2zsZjelerjX", "name": "Dadju"},
    {"spotify_id": "2UwqpfQtNuhBwviIC0f2ie", "name": "Damso"},
    {"spotify_id": "66Ok6bgC570sHkw08N20pZ", "name": "OBOY"},
    {"spotify_id": "4FpJcNgOvIpSBeJgRg3OfN", "name": "Orelsan"},
    {"spotify_id": "5gqmbbfjcikQBzPB5Hv13I", "name": "Gazo"},
    {"spotify_id": "4eYnorQRhVHT2KBl2UyHHd", "name": "Vegedream"},
    {"spotify_id": "4QSTyDpxsKmv3UfavVUImR", "name": "Darkoo"},
    {"spotify_id": "3DCWeG2J1fZeu0Oe6i5Q6m", "name": "PLK"},
    {"spotify_id": "7CUFPNi1TU8RowpnFRSsZV", "name": "Niska"},
    {"spotify_id": "1q7T9rFQ2a2ukA1PU51fo3", "name": "Koba LaD"},
    {"spotify_id": "0GgY7hjMoGDsX8ZDe2mwds", "name": "Soolking"},
    {"spotify_id": "2kXKa3aAFngGz2P4GjG5w2", "name": "SCH"},
    {"spotify_id": "0FEJqmeLRzsXj8hgcZaAyB", "name": "Indila"},
    {"spotify_id": "4LXBc13z5EWsc5N32bLxfH", "name": "Nekfeu"},
    {"spotify_id": "6L34dW6SKMSDaGIfYDU19j", "name": "Maes"},
    {"spotify_id": "3NH8t45zOTqzlZgBvZRjvB", "name": "PNL"},
    {"spotify_id": "7xNYY1Zkb1vks5m9ATlJok", "name": "Naza"},
    {"spotify_id": "0oeiA5U9u1U45Gos5cywUU", "name": "Soso Maness"},
    {"spotify_id": "76Pl0epAMXVXJspaSuz8im", "name": "Freeze Corleone"},
    {"spotify_id": "3YwqjMyrRfuixi2pbgTGCE", "name": "Heuss L'enfoiré"},
    {"spotify_id": "4WnAHZz1pgl8hus8hidIRV", "name": "MHD"},
    {"spotify_id": "4BFLElxtBEdsdwGA1kHTsx", "name": "ElGrandeToto"},
    {"spotify_id": "2z2TRvloJt4EfUNQp9rHAi", "name": "Alonzo"},
    {"spotify_id": "46wEUZyujVrFSrdCnTKQmV", "name": "Marwa Loud"},
    {"spotify_id": "7DUTsWY3RBd64vh8UtgtYA", "name": "Lacrim"},
    {"spotify_id": "58wXmynHaAWI5hwlPZP3qL", "name": "Booba"},
    {"spotify_id": "3CnCGFxXbOA8bAK54jR8js", "name": "Vald"},
    {"spotify_id": "791x09Ix1mNc1hGhbD7IOW", "name": "Le Classico Organisé"},
    {"spotify_id": "4uJNQGa3L2frXDxwgouTIw", "name": "Franglish"},
    {"spotify_id": "3J7r4VsNmuWixU0nXvyPd8", "name": "Kalash"},
    {"spotify_id": "2RJBv9wXbW6m539q9NOfW1", "name": "Soprano"},
    {"spotify_id": "05hirnMeVIzCrcUxbrysZU", "name": "Hatik"},
    {"spotify_id": "3vUMXQ9kPnZAQkMkZZ7Hfh", "name": "Tiakola"},
    {"spotify_id": "6HCBnyTBSLdb3TFn2ayulY", "name": "Leto"},
    {"spotify_id": "5RaQ9nmVGoTye2SI76x3yw", "name": "Kofs"},
    {"spotify_id": "5gs4Sm2WQUkcGeikMcVHbh", "name": "Hamza"},
    {"spotify_id": "5hREZP0zTQbTLkZ2M8RS4v", "name": "Djadja & Dinaz"},
    {"spotify_id": "1ntQKIMIgESKpKoNXVBvQg", "name": "Kaaris"},
    {"spotify_id": "6HhnhnxLsowYuuejvku0Bz", "name": "Lartiste"},
    {"spotify_id": "2ubn2zwyYaLdHOCKnTouU2", "name": "Ziak"},
    {"spotify_id": "2ptKt4yP4mYRZmvi09JYyi", "name": "Timal"},
    {"spotify_id": "2EFpb61Lpi0l5ldOiqbZkK", "name": "Landy"},
    {"spotify_id": "2eh8cEKZk4VeruUrGq748D", "name": "Rim'K"},
    {"spotify_id": "3PsyPWjsftbfeXGorZv4AM", "name": "Grand Corps Malade"},
    {"spotify_id": "1kwzW1IszUiq4Gs9BFesvW", "name": "Hornet La Frappe"},
    {"spotify_id": "6ytOHdKh4xt4YvF7tz8Zcv", "name": "Kalash Criminel"},
    {"spotify_id": "3tTvSeZiFDP3CY5EdPGcR4", "name": "ASHE 22"},
    {"spotify_id": "6qFt3TjvxMt77YGsktWG8Z", "name": "Sofiane"},
    {"spotify_id": "2IoSLl3tqYMq9DzR0d6NJN", "name": "Elams"},
    {"spotify_id": "1QPdp5duV6lV4XINCzjwQ2", "name": "Dinos"},
    {"spotify_id": "1Yfe3ONJlioHys7jwHdfVm", "name": "Lomepal"},
    {"spotify_id": "2kIs76sEGiulKeqetZq6ua", "name": "Jok'air"},
    {"spotify_id": "2tcoLkA9Hexz70Kuc1NTUl", "name": "Gradur"},
    {"spotify_id": "3ASAxVN1hNoYfoMcIkzZWL", "name": "VillaBanks"},
    {"spotify_id": "19u3RGWKsjmbg9eI6zAiNp", "name": "13 Organisé"},
    {"spotify_id": "0LnhY2fzptb0QEs5Q5gM7S", "name": "Laylow"},
    {"spotify_id": "4krMq8pXkLVTGplpYgHlnV", "name": "Ronisia"},
    {"spotify_id": "7x3eTVPlBiPjXHn3qotY86", "name": "KeBlack"},
    {"spotify_id": "2pHk4wAmL7ofTAuvCIUWtv", "name": "Roméo Elvis"},
    {"spotify_id": "3xEJ7cDz5rdg6VM8E6Mqhf", "name": "DA Uzi"},
    {"spotify_id": "4Ue6MAZqz18NlaOQomRXLU", "name": "1PLIKÉ140"},
    {"spotify_id": "07h4CCFmlXkwx0g4PL5Uuh", "name": "Guy2bezbar"},
    {"spotify_id": "74YbW6s8CZdaYLxJU9HeS7", "name": "Mister You"},
    {"spotify_id": "1wAtSe79kItIb9nf5EhI2Q", "name": "Niro"},
    {"spotify_id": "5NlA3ayVBDY3uDCCEZ1dID", "name": "Rook1e"},
    {"spotify_id": "4vnmifnGOeRXfNTRtgd4Tj", "name": "Sexion d'Assaut"},
    {"spotify_id": "0LKAV3zJ8a8AIGnyc5OvfB", "name": "SDM"},
    {"spotify_id": "4MRRW42s9ymwa5zu4xTKJh", "name": "Kaza"},
    {"spotify_id": "0gGcw3tA1fZoF23qa8KFb7", "name": "Bolémvn"},
    {"spotify_id": "6Mm2g25BTeJ6BICPFWGkPg", "name": "Bosh"},
    {"spotify_id": "5olcgTzelGdyP1rHRLyWgs", "name": "S.Pri Noir"},
    {"spotify_id": "25yJrwrn5I0EUdQEiTtNSO", "name": "Lefa"},
    {"spotify_id": "54kCbQZaZWHnwwj9VP2hn4", "name": "Zola"},
    {"spotify_id": "4RB2EEsmLhQTOSVQQpDzNg", "name": "Sofiane Pamart"},
    {"spotify_id": "7rFugkk9ZvVB1zXHg8h0rj", "name": "Eddy de Pretto"},
    {"spotify_id": "5DW7NxqQ2875JtjuV7KMn4", "name": "Youssoupha"},
    {"spotify_id": "3b5bg1k6N9u31OtzSfK2dP", "name": "Dosseh"},
    {"spotify_id": "6dbdXbyAWk2qx8Qttw0knR", "name": "Josman"},
    {"spotify_id": "1eTRyiHsWMoWKPD6s4Kiqt", "name": "Lujipeka"},
    {"spotify_id": "7kyIBL1EYouLqC8vw7IOui", "name": "L'Algérino"},
    {"spotify_id": "7FXX45sHqoQoCwqtG0ZV8H", "name": "Solda"},
    {"spotify_id": "7w1eTNePApzDk8XtgykCPS", "name": "Malaa"},
    {"spotify_id": "35B6bq5keTR1PYEahq1TAF", "name": "Sasso"},
    {"spotify_id": "0qO3t2MHM5NIEJ5fw9VndY", "name": "Benab"},
    {"spotify_id": "78Die3Gb8yaElTmGCa7m7N", "name": "Kore"},
    {"spotify_id": "6o5sl0TGublDPXyMHdMq1E", "name": "Moha K"},
    {"spotify_id": "6CSKMBCeQhddsPL63zvDhX", "name": "Dj Leska"},
    {"spotify_id": "0cMsSWXCY2Wag16luxN6fL", "name": "Jazzy Bazz"},
    {"spotify_id": "3UHc2YZGHYS6TEYMJeDf1D", "name": "YG Pablo"},
    {"spotify_id": "3dH7pcBScIJQboDyMzUzez", "name": "GLK"},
    {"spotify_id": "6379rD5bSEwInazkKhZ9DM", "name": "Diam's"},
    {"spotify_id": "32UhRcgdXO6LdLhOpfIdxp", "name": "Rohff"},
    {"spotify_id": "2ktpq7bp4m1quizyEmp4r1", "name": "A2h"},
    {"spotify_id": "5U05AU34EcZ8pfohg2dicI", "name": "UZI"},
    {"spotify_id": "3mTLkUsH6xz7b0UjcNcVsN", "name": "Driks"},
    {"spotify_id": "5qisLjDrKoHMI9zOK2hfzs", "name": "Mister V"},
    {"spotify_id": "2GlEiSHYEKlq9cUYDa9oZb", "name": "Lynda"},
    {"spotify_id": "1lB3I3SI30v2ZOpR4XQqzJ", "name": "Gambi"},
    {"spotify_id": "69irZ4R8OsrLHjr6VmMmMg", "name": "Gaël Faye"},
    {"spotify_id": "2yJ6lsLqG06r9bckSTQRt4", "name": "Zkr"},
    {"spotify_id": "62zLrboqOTPyozwi721CVy", "name": "Lorenzo"},
    {"spotify_id": "0aXaZj4wB5jLF2E2d8WEVi", "name": "47ter"},
    {"spotify_id": "0SXZ0s0MoLOjw4Af6i3OGC", "name": "Tsew The Kid"},
    {"spotify_id": "0zhMujl1yB8pkB023Qm4Y2", "name": "Green Montana"},
    {"spotify_id": "1cA379ILgR07m7XQVXyP6Q", "name": "Sneazzy"},
    {"spotify_id": "5Y5EJ20jDQkkB213zwuDXR", "name": "Menace Santana"},
    {"spotify_id": "63MCBZRiUdnqRsAOJwijiB", "name": "Sadek"},
    {"spotify_id": "5mmEMfYChd6MImBagU7zCs", "name": "Bigflo & Oli"},
    {"spotify_id": "7yeFMUrYTY5cAZx0GKXnti", "name": "Alpha Wann"},
    {"spotify_id": "4TGltjqP0MQxdGeSIrM4es", "name": "RIDSA"},
    {"spotify_id": "2k8fAJK9HbH1FhqVpZL98P", "name": "YL"},
    {"spotify_id": "6Pr9pssRV0tD0jdh2Z84td", "name": "SAF"},
    {"spotify_id": "2s7fZ34RK8RUJQ2ewsh6I5", "name": "RK"},
    {"spotify_id": "3AGggQTwJaSofLcpDlYhV4", "name": "Still Fresh"},
    {"spotify_id": "4vtz0m60CCrcsQmqDunDIR", "name": "Moha La Squale"},
    {"spotify_id": "7lMgpN1tEBQKpRoUMKB8iw", "name": "Black M"},
    {"spotify_id": "37ioGUZGhKk7VjWIocx8kM", "name": "DTF"},
    {"spotify_id": "5QuZ9HdvnXcX8kEG782Phv", "name": "Le Rat Luciano"},
    {"spotify_id": "1E8w172gkuT5htpwaIEsEl", "name": "Népal"},
    {"spotify_id": "4xTiWBThjZgo1uZn1WpZm3", "name": "DJ Hamida"},
    {"spotify_id": "2HPiMwJktBXqakN0hnON2R", "name": "Lous and The Yakuza"},
    {"spotify_id": "20pbz4TbpkBUr5JwYfGgPS", "name": "Kekra"},
    {"spotify_id": "3bRGJQd7b4lE3ZAEMfOXJp", "name": "Luidji"},
    {"spotify_id": "0YqeL4iGLLNiwRXZvew1TM", "name": "Larry"},
    {"spotify_id": "1HH5TlkjRt2FG8dpkWNm5j", "name": "ISK"},
    {"spotify_id": "6Xc0KDqzw5u6EQLgdfeoKO", "name": "Georgio"},
    {"spotify_id": "0Yj3N31EWXHc6e3eDyJPLP", "name": "Lyna Mahyem"},
    {"spotify_id": "1WDkNp8Duv9QhO246S4dDa", "name": "Bramsito"},
    {"spotify_id": "1SxuyHZnLUFyFHGzdGaxZk", "name": "Wejdene"},
    {"spotify_id": "6BbceEVcjow8mhQPYK3eBK", "name": "Skread"},
    {"spotify_id": "5Ea2kDQeQNQrIcI6tCthaQ", "name": "THABITI"},
    {"spotify_id": "0xEVr5H3VEj3g11u1q6ifW", "name": "MZ"},
    {"spotify_id": "5AAzeysphag0NxJxLbbVla", "name": "Columbine"},
    {"spotify_id": "1PTl9q5EaEZejVGts7MBLN", "name": "Mac Tyer"},
    {"spotify_id": "0vN920jukdAbErvjo2OJ2o", "name": "Zaho"},
    {"spotify_id": "3MNnSV5hDd2UzZzgqD8xlU", "name": "Shay"},
    {"spotify_id": "2LUi4eKMEFKFM4awgurcSs", "name": "4Keus"},
    {"spotify_id": "4oVERQ0AxzzQ4zip1nMKlt", "name": "Gringe"},
    {"spotify_id": "56Q6weEROZ1RsVrTak8Bm7", "name": "IAM"},
    {"spotify_id": "7J0JxtOPMKWufOraoIqjiH", "name": "JSX"},
    {"spotify_id": "5VkemxUDiz46ZHPdvh0LX0", "name": "ICO"},
    {"spotify_id": "7rz6ZZErn5YFDteXKhyf3g", "name": "Disiz"},
    {"spotify_id": "5l8WyvJ50fdSghK2ySNq1y", "name": "Luv Resval"},
    {"spotify_id": "6IflU2YrY5Cyw7YoBICosV", "name": "Fally Ipupa"},
    {"spotify_id": "3x3gsBtmPOSQVqdBzO7N5E", "name": "Nahir"},
    {"spotify_id": "1ywkNtrO3WGuwaehqxyjAO", "name": "Chilla"},
    {"spotify_id": "76OnsMFi0V8EsscskTGEch", "name": "Lucién"},
    {"spotify_id": "1qBSTVOOFSTKWn3TQUtWqw", "name": "Cut Killer"},
    {"spotify_id": "4YUcg2ee9TxMNdjhAxzZBF", "name": "Ashh"},
    {"spotify_id": "64XqdWjtYhfMJeQB7wtAwS", "name": "Hiro"},
    {"spotify_id": "0mnNM5o7vtxo3ivC7Tmoah", "name": "Chily"},
    {"spotify_id": "15LZyW96TXq91lUBjMHQok", "name": "Squidji"},
    {"spotify_id": "1FiWBzw15KbR9amOb1Xnxp", "name": "Odezenne"},
    {"spotify_id": "44bvfFf9VeGwVjK0QDqQ7O", "name": "Oxmo Puccino"},
    {"spotify_id": "3nU8TSIICYDbUqRpJISTRE", "name": "MC Solaar"},
    {"spotify_id": "6TMBV8J3Jq1Gr5A5bFmVqf", "name": "Laeti"},
    {"spotify_id": "5sXx89ZqVFOUKTl5g2uiST", "name": "Casseurs Flowters"},
    {"spotify_id": "1rT9J8vtPCzEKL7oGntxnr", "name": "Rémy"},
    {"spotify_id": "6QS84S3i4gwdEKqWoTtDLd", "name": "La Fouine"},
    {"spotify_id": "1HhXce8PpMmaKjBIWzAxWc", "name": "S-Crew"},
    {"spotify_id": "5CtPAGoxpJ4yLJLx6CSrO8", "name": "Zamdane"},
    {"spotify_id": "4ko6Ysxtvx9EY9GEFslrIz", "name": "Suprême NTM"},
    {"spotify_id": "23u2dvae3e0f3caJSqdlN5", "name": "SenSey'"},
    {"spotify_id": "2h5IzYxNFBtXa3PsnV370c", "name": "Klem Schen"},
    {"spotify_id": "3U0pUvFUMv6gJiTFnXiueY", "name": "KIKESA"},
    {"spotify_id": "3fnfvu19t4JYyEkRldXsO5", "name": "Kodes"},
    {"spotify_id": "1ssrFpfMmM0vRx85eO2XKL", "name": "Fresh LaDouille"},
    {"spotify_id": "76wDwepIombkHCdm0kas1h", "name": "Tawsen"},
    {"spotify_id": "4hYxvgmTzS29XAXlo5adgM", "name": "L2B Gang"},
    {"spotify_id": "04AIS3XqFcq2k8w3Tx4AmU", "name": "Siboy"},
    {"spotify_id": "2sBKOwN0fSjx39VtL2WpjJ", "name": "La Fève"},
    {"spotify_id": "5vnUF9uAL0ly7qw25ERLuC", "name": "TK"},
    {"spotify_id": "01fkQiYuBZt16vQ8iRIc7g", "name": "Sopico"},
    {"spotify_id": "3mKyKC4BjNrNJSSBSrNy0a", "name": "Mig"},
    {"spotify_id": "1afjj7vSBkpIjkiJdSV6bV", "name": "Médine"},
    {"spotify_id": "3jrZXTzqSuTBdfJeoSts1n", "name": "Anas"},
    {"spotify_id": "6k68jYvlUy3CXOwhG1NDBL", "name": "Manau"},
    {"spotify_id": "5FK0v12GGmqj8kzmiWDPRT", "name": "2TH"},
    {"spotify_id": "7rTPCNINGzMp3Hc8Xqht5Z", "name": "13 Block"},
    {"spotify_id": "1cYA2rnKwpVYe9iVH3Djjm", "name": "Yuzmv"},
    {"spotify_id": "3BX2N7cc1OrBUJQiiei3On", "name": "L'Allemand"},
    {"spotify_id": "7uzKFCBLb6SLQ5c4ML6fQw", "name": "DOXX"},
    {"spotify_id": "4J3vhZNPel1Tyj2GHsXi6i", "name": "Moji x Sboy"},
    {"spotify_id": "71x0OO2toFjXrMRcufL9tv", "name": "Poupie"},
    {"spotify_id": "6FyY3mlFrDdKUX35GrzeOZ", "name": "Smeels"},
    {"spotify_id": "1AKP8Tnz8KfOdRM4mqvNtF", "name": "Lala &ce"},
    {"spotify_id": "71XOKoFKWFjlV91e2Z5r21", "name": "Frenetik"},
    {"spotify_id": "6sYR8JTRUUUzSD9IydLhfG", "name": "Guizmo"},
    {"spotify_id": "5f6nz3iqzrfiUfKOIKvLvd", "name": "Nemir"},
    {"spotify_id": "1i8gGjDzv2FNoy6dHcr25K", "name": "Negrito"},
    {"spotify_id": "1nTVNdaDAzXB1AbP30cGk6", "name": "SNIPER"},
    {"spotify_id": "3yTebTUCCcdO6f6RN7vVlY", "name": "Taïro"},
    {"spotify_id": "5oDxGfxYaJkfp6xZlXQnr8", "name": "Fatal Bazooka"},
    {"spotify_id": "3sOh3Pok0NReizHRp4ochp", "name": "Livaï"},
    {"spotify_id": "1ONnyhQBTnkvg4QmI97hJg", "name": "Sinik"},
    {"spotify_id": "5gU8eqolA1bziWv6e3Wjp3", "name": "Django"},
    {"spotify_id": "37S0GFsBW73uqxGXNFeADJ", "name": "Ghost Killer Track"},
    {"spotify_id": "7B8kPWR00p96IXVH6u4zrf", "name": "LVZ"},
    {"spotify_id": "5nTMNNNwQMoCYgzUXdUaB6", "name": "113"},
    {"spotify_id": "12rqcxsx28NPNRwPOEBxYG", "name": "Kalif Hardcore"},
    {"spotify_id": "3ABLHSKKZzNcgpBuXvLB9W", "name": "Kpoint"},
    {"spotify_id": "1mMUzAMrNqoTHgtxA0dZi6", "name": "Caballero & JeanJass"},
    {"spotify_id": "0ZCX1rGywF2LATUUCq0nOg", "name": "EDGE"},
    {"spotify_id": "5ydAcIK2KdpBIbL0yGFJle", "name": "Kery James"},
    {"spotify_id": "3gz8sBWqcMQ0qsrZIoVphx", "name": "Hayce Lemsi"},
    {"spotify_id": "4yLgYK2B5nZjZMBiaLyLyK", "name": "Doums"},
    {"spotify_id": "63hFhXYW3r2q8uW2Rf3LUw", "name": "H Magnum"},
    {"spotify_id": "2dpE5iOVyp0bLTb7a15gkG", "name": "La F"},
    {"spotify_id": "2NRdZaTYZk1CexnDSlnxZU", "name": "MadeInParis"},
    {"spotify_id": "3S8r9fkqybCCXJLhZGA3r1", "name": "Cinco"},
    {"spotify_id": "09E5z6upwkmwTKX8LGQgMo", "name": "Yaro"},
    {"spotify_id": "3L774tiJRvPmAS90pOLB44", "name": "Rsko"},
    {"spotify_id": "2GBDOaCl73BVUs2RerIme7", "name": "Corneille"},
    {"spotify_id": "2xdTZfuOFh2ylOnnTEs5sg", "name": "Gambino La MG"},
    {"spotify_id": "2OTfhbxhBO1u1bAuCy6ouu", "name": "Deen Burbigo"},
    {"spotify_id": "2vCOfKQ7WFyWmuHbTz7OgG", "name": "Says'z"},
    {"spotify_id": "7qiRNP9z0FhN63YcLmb8Ai", "name": "Stupeflip"},
    {"spotify_id": "7jUHzlUQxkrsszeYAIqHCY", "name": "Kanoé"},
    {"spotify_id": "3nDLTOGw0WwwddP3tq5561", "name": "Coyote Jo Bastard"},
    {"spotify_id": "4bDcCV0zjPsVs2GxtduYry", "name": "Captaine Roshi"},
    {"spotify_id": "2GIoAorOnT0Yp1jKyTzW7K", "name": "BU$HI"},
    {"spotify_id": "3IMC79WXhjXUkDHhpsSN8n", "name": "FouKi"},
    {"spotify_id": "11jTIrOwxFOLvhJIdb4FYo", "name": "JeanJass"},
    {"spotify_id": "1LYOKaB67uPrzpNMIk10k9", "name": "Brulux"},
    {"spotify_id": "6AmKZ6kQdFR64iIiUsRMHT", "name": "Graya"},
    {"spotify_id": "0QcZD8V0Ug1KINWBSyG0dB", "name": "Alkpote"},
    {"spotify_id": "2jFnPm8VeSO19i6B8blXB5", "name": "Abou Debeing"},
    {"spotify_id": "20amiDsCI5EwB6xy37h44k", "name": "MMZ"},
    {"spotify_id": "6XaUaXu0cGAFK1AlQkl1b6", "name": "Saian Supa Crew"},
    {"spotify_id": "6p4AluOj2RxnUuPWwZLTxN", "name": "Féfé"},
    {"spotify_id": "5un78gf3HzGs8Kgeoflgna", "name": "DJ Erise"},
    {"spotify_id": "1FhFAnXsMLYJhRVBKvcdHU", "name": "PRIME"},
    {"spotify_id": "5MJkroCz5vy8h3LeDsN1vu", "name": "Ichon"},
    {"spotify_id": "6mA4csYsYvf4Mq02PleZEV", "name": "20syl"},
    {"spotify_id": "5dacK0fiMwLoV93yBdUrZK", "name": "Sifax"},
    {"spotify_id": "2XyVj5qsjy87RPXk1O5if3", "name": "Alrima"},
    {"spotify_id": "1C2qs1UQDDtf7N1XrS2lcW", "name": "Nèg' Marrons"},
    {"spotify_id": "4wuKH89QtnyauwNpBMp5RP", "name": "Hugo TSR"},
    {"spotify_id": "0OQMxt6l70FM2YlLwYDiEn", "name": "Swing"},
    {"spotify_id": "0lCzbSVa8RZoPsuDM9YBJS", "name": "Tiitof"},
    {"spotify_id": "5DE0by3fZT0nrlJSutY2D7", "name": "Caballero"},
    {"spotify_id": "1h0vYLWMAElSWYCjm6RBpe", "name": "Ikaz Boi"},
    {"spotify_id": "6vclJnUiJ9D7IW0OP54MFT", "name": "Fredz"},
    {"spotify_id": "6IYoNcihnYWgtCHRTLxk7H", "name": "Nessbeal"},
    {"spotify_id": "4ddg7PH5OuSossiSBWgueu", "name": "Akhenaton"},
    {"spotify_id": "1uS3NoifQsUXbWBOF3xIPg", "name": "Nakry"},
    {"spotify_id": "22I8wvU1Zw6EMiOt4W98BN", "name": "Arma Jackson"},
    {"spotify_id": "5SZayIKDZvxXaJrxLfnIRN", "name": "Seth Gueko"},
    {"spotify_id": "2BEMYnNYVY6FScCvRaw1J6", "name": "Mehdi Yz"},
    {"spotify_id": "61y0Qj5xUcKnbHYxuaqSRP", "name": "Myth Syzer"},
    {"spotify_id": "6RwBaA9wZC0BPWZfmGeWMo", "name": "Krisy"},
    {"spotify_id": "7fRBY7RRf4iMn2Z4bhZcYA", "name": "Scylla"},
    {"spotify_id": "2UZBLsGKZZnYDb37cDM13m", "name": "Le Dé"},
    {"spotify_id": "5iu7PzNW2d8xKOE8IsXgef", "name": "Lonepsi"},
    {"spotify_id": "3rF2ZcZCcwYluO3h9wRP22", "name": "An'Om"},
    {"spotify_id": "0VF7XcB73fBSIfX9hOTVij", "name": "Dabs"},
    {"spotify_id": "0K4D8NX2d2sMQlvWcfLhSL", "name": "Ocevne"},
    {"spotify_id": "3p6dh3Zn4fVXJatMy3Xqzq", "name": "Osirus Jack"},
    {"spotify_id": "3r03pmZDGQnWxIeWE4TsOq", "name": "Suzuya"},
    {"spotify_id": "3tNQ0aWtzDKGwyWz2oOAFG", "name": "Kamikaz"},
    {"spotify_id": "40fhusTxvAWqq7xKB2rlgf", "name": "Ghetto Phénomène"},
    {"spotify_id": "0IhPOW5cO2phSUCYqWuTTb", "name": "Gotti Maras"},
    {"spotify_id": "1ufm09MhiuoHpIFkbcIZGx", "name": "Fababy"},
    {"spotify_id": "1BTmMBPzv3zEO3f6ilFoct", "name": "Fonky Family"},
    {"spotify_id": "4CH2uNha7qT33gsr1y60Ca", "name": "1995"},
    {"spotify_id": "1qz3nYVQit24tcOsCOdCvb", "name": "Cupidon"},
    {"spotify_id": "0DhhGFA0yxKhk7wrnzdbbK", "name": "Lossa2Squa"},
    {"spotify_id": "3RJNCnIkqvVwEicgGo2nqJ", "name": "Dinor rdt"},
    {"spotify_id": "67MIpliQaIhUN1WLSkYEqC", "name": "Le Juiice"},
    {"spotify_id": "0DjR09NBgtZbkOnBZays9o", "name": "Chiloo"},
    {"spotify_id": "2quhaEEtVvUNS0HwL1EJNn", "name": "Benjamin Epps"},
    {"spotify_id": "2PVg2kfkw7jNNVfy6ouB3H", "name": "Kpri"},
    {"spotify_id": "2T94BUd6X8J1G5EfJj3hZr", "name": "Lunatic"},
    {"spotify_id": "6SWyMvHN1YLZ95qwbKf26N", "name": "Norsacce Berlusconi"},
    {"spotify_id": "4LuLF5H9fe5ViyDQb9Zxmt", "name": "Key Largo"},
    {"spotify_id": "2CLtDhw1uJe59E3P56JN6T", "name": "Psy 4 De La Rime"},
    {"spotify_id": "3IG4wXzUoG2sb1895LQZIl", "name": "Foda C"},
    {"spotify_id": "5A7u47fziMdcEMunHjT8Kf", "name": "MALTY 2BZ"},
    {"spotify_id": "13fQpdj4xMKM4gbQUcB00T", "name": "Moha MMZ"},
    {"spotify_id": "5h0VUGq3Pn45E3rcz9oe66", "name": "Dry"},
    {"spotify_id": "5P3mgWx3KvnURMhlVm5pMS", "name": "Youv Dee"},
    {"spotify_id": "281AuR0rWkBECMeaAB0pSA", "name": "Ateyaba"},
    {"spotify_id": "5DEZRgl7H5KUdzo5YGvyk7", "name": "Oby One"},
    {"spotify_id": "1ZjPqYngrwDa5ZqwAPcj5o", "name": "Shurik'n"},
    {"spotify_id": "7CPznx8a1emLVLeCHGuJeN", "name": "Lord Esperanza"},
    {"spotify_id": "0dSh0CIa0HPd9kJmJSmGQo", "name": "ISHA"},
    {"spotify_id": "0zfnSBlLA4HJshaxPu2zPV", "name": "Mallaury"},
    {"spotify_id": "4fn6Kez1kGOO74vNuKrvCU", "name": "Hös Copperfield"},
    {"spotify_id": "29sSh43yox3SqzghBzwn7x", "name": "Pirate"},
    {"spotify_id": "6cDxDe1MWGgUcNVVdxhCN2", "name": "TripleGo"},
    {"spotify_id": "3U1jsFYwwJHv7VB4Frf3F4", "name": "TyFontaine"},
    {"spotify_id": "2Sm4rGKWBnOQhdqDy4JJh0", "name": "Zwangere Guy"},
    {"spotify_id": "65LSKdbofg1NdWkaLSVXKc", "name": "Nuttea"},
    {"spotify_id": "3mvmdWXXKKpUrmYTvdALyS", "name": "Sam's"},
    {"spotify_id": "6a2V6IHS7jT9M1IvJ8V3yB", "name": "Zuukou Mayzie"},
    {"spotify_id": "6aH4CaxRV988XUNLVSi1dZ", "name": "T2R"},
    {"spotify_id": "4fj5OWrMmlCbrc3PocAcl1", "name": "J9ueve"},
    {"spotify_id": "3YBJLs7RqR0aPGBgU27nDh", "name": "Werenoi"},
    {"spotify_id": "3viUmbbKSqgMFOVHfrZQpn", "name": "Davodka"},
    {"spotify_id": "3viiIGEp9jn0sKz4K0D6HT", "name": "DAVINHOR"},
    {"spotify_id": "4uQFbbElr6aB0P0wNULI9t", "name": "Yung Trench"},
    {"spotify_id": "11ajgggOI6hGjR8CF53mhG", "name": "F430"},
    {"spotify_id": "5Txlp4Pwg0rWyrIQaqnAUG", "name": "Gracy Hopkins"},
    {"spotify_id": "4OZ0VK1N3PDtGhY2d6sqhI", "name": "Clem Beatz"},
    {"spotify_id": "1nODcAdzs2eLjAp6AsrMzA", "name": "Michou"},
    {"spotify_id": "2OULCPo7k0vPKlEZimhaVc", "name": "Sefyu"},
    {"spotify_id": "5DXzQwj6Kgr5kBjVlYdSHo", "name": "Loud"},
    {"spotify_id": "52h6A1y99QgoEf5FzKEHs1", "name": "Diddi Trix"},
    {"spotify_id": "3ssUeoVViu1S2RGl1hLmUh", "name": "Al'Tarba"},
    {"spotify_id": "5W9ShLREoRMuXqSSYMeHqk", "name": "Gianni"},
    {"spotify_id": "4ZW7BptOWzjNFLEqRiNCT7", "name": "So La Lune"},
    {"spotify_id": "0DrzKyq66BJLP9V5IjiE4d", "name": "DJ Babs"},
    {"spotify_id": "7uN1aqKCrD6Ju1sn74MPgf", "name": "Singuila"},
    {"spotify_id": "36MWnDH4kn3Sx79LLtLpjF", "name": "Zeu"},
    {"spotify_id": "468tlC6QAKEJ4u0jndX9o0", "name": "Vicky R"},
    {"spotify_id": "3fREHN5zWLjSlRzicDxE3c", "name": "SEB"},
    {"spotify_id": "2vVtmqEXliBFxqCa3Juo5W", "name": "Niaks"},
    {"spotify_id": "4GX9CqwqWtb76wuXwbXR6b", "name": "Doc Gynéco"},
    {"spotify_id": "1EQnOqZu9A0liA8XcYuMGu", "name": "Validé"},
    {"spotify_id": "4m90Zo0X5ACTTk27IZ9eMY", "name": "MRC"},
    {"spotify_id": "4QGic2UQwhraaN63znXHMu", "name": "PRAYER"},
    {"spotify_id": "6kvvDgFMvd02LlVlGX55GN", "name": "Dala"},
    {"spotify_id": "2rxubOde1svVDYAVDy7PDS", "name": "Asdek"},
    {"spotify_id": "6wjkiUBMMYSIx5UBTp7eKC", "name": "Bekar"},
    {"spotify_id": "1pQtc9O0CKJYhvaICw39z9", "name": "DENZO"},
    {"spotify_id": "0WzzOQ8n065ISKclSusFzY", "name": "AM La Scampia"},
    {"spotify_id": "0JxUh8qDlG3xflSV9Of500", "name": "100 Blaze"},
    {"spotify_id": "0HdLXCWPtmK9wgd7CyNuj3", "name": "Le Motif"},
    {"spotify_id": "7r65N4pfWPM7D0zKe86jgk", "name": "Gros Mo"},
    {"spotify_id": "4z8LvfxawVZLoLR1KTUzQL", "name": "Dooz Kawa"},
    {"spotify_id": "4ddqz1AzqYMRKYTslXO839", "name": "Doria"},
    {"spotify_id": "2bbQRkTmEgKA1INGHeH7oT", "name": "Cheu-B"},
    {"spotify_id": "7hChnO6TKesBmtbTFFjYbP", "name": "Kemmler"},
    {"spotify_id": "5k7czLtvpvADY4FkRnTS4p", "name": "Joanna"},
    {"spotify_id": "7rjPaOQdQeTIQhmApviFqe", "name": "Zikxo"},
    {"spotify_id": "6y9D9asiDbnfHSZETC6pkZ", "name": "Kaneki"},
    {"spotify_id": "1D5DI6S5zIiGPBf1IAuAJh", "name": "Hocus Pocus"},
    {"spotify_id": "1AT8NKdQOU0EVPu6ehN4NA", "name": "Meryl"},
    {"spotify_id": "2UnQkf0SLOpeAUAiOGvwfq", "name": "Popey"},
    {"spotify_id": "2t0frJEIdex2PTwuLlGxDD", "name": "Carbonne"},
    {"spotify_id": "3xQiLcsmj0KCiFtconY6Dz", "name": "Demi Portion"},
    {"spotify_id": "1xAkr1syMoClC66pHMk2Eq", "name": "La Synesia"},
    {"spotify_id": "5y2Ny3eOPrhtb5uQFl30vq", "name": "Infinit'"},
    {"spotify_id": "7grHO7fIKR0mfOLo5BEFBl", "name": "Minissia"},
    {"spotify_id": "4kAzmAcboZ0F6bCCb4jj8I", "name": "Spider ZED"},
    {"spotify_id": "5ffMSKGQRhetAjBjEgkRun", "name": "DJ Mehdi"},
    {"spotify_id": "2dZM3D9rBveK3dywr1WQkN", "name": "Alliance Ethnik"},
    {"spotify_id": "5WXxrPG1ifx9gOa5mHMm0o", "name": "El Matador"},
    {"spotify_id": "0Q5EUbHvUWlYpSwmKKbUSF", "name": "Keny Arkana"},
    {"spotify_id": "1enyZzjGFn1UNdk8EqeicI", "name": "Tisco"},
    {"spotify_id": "6jMwNySNrAokQ3Gv8opEP7", "name": "Tunisiano"},
    {"spotify_id": "41o2A93SPxIUxsy5HQjvul", "name": "Passi"},
    {"spotify_id": "5r4KrJXWxLsbym4vjcRv1i", "name": "Tandem"},
    {"spotify_id": "6vYIofTPb6utQIovHOFyG3", "name": "LE RISQUE"},
    {"spotify_id": "3msewJ0hXf2THwcdYjGeOA", "name": "Ménélik"},
    {"spotify_id": "24lRU7Y7ZWpVa3v23FZqS6", "name": "Jewel Usain"},
    {"spotify_id": "0iTL62LjPPI99dA62aW0Ir", "name": "Pbenz"},
    {"spotify_id": "3p4FNslxuuEYSEnMsx4YI1", "name": "Hooss"},
    {"spotify_id": "626MEj1uIFt7eZMSroO01a", "name": "Shotas"},
    {"spotify_id": "2XpsF0ZQfBV08auUoRnNJE", "name": "Liim's"},
    {"spotify_id": "7JDQ2kZsT80ht4tzgIaId4", "name": "4Keus Gang"},
    {"spotify_id": "7x2hBF3bNPwW9PnKxg9Zf8", "name": "OUENZA"},
    {"spotify_id": "4TEnXYHvYwoMopWqxeAnTE", "name": "Admiral T"},
    {"spotify_id": "2lPL3aVXBS4gVGymFOAYxF", "name": "L'Or du Commun"},
    {"spotify_id": "6nxnoznWVrq1HXBbjl2cz3", "name": "Lycos"},
    {"spotify_id": "3KQ6K5tg4iklLDO1cNnunn", "name": "Bené"},
    {"spotify_id": "5ZtIEcmzQosu8SDKWgwc86", "name": "Scred Connexion"},
    {"spotify_id": "7DPKgW7yJcdwHC2HLStxti", "name": "Koffi Lossa"},
    {"spotify_id": "2TM7WyJwjfD5wKyX9OtIWJ", "name": "Zed Yun Pavarotti"},
    {"spotify_id": "43MnKJFpiqBVhI0jnOjZj4", "name": "Salif"},
    {"spotify_id": "3Rz9ULXMl7mfhCCFNnhd5N", "name": "ZeGuerre"},
    {"spotify_id": "2NXFKDjgSuIyiUUH2PEVHG", "name": "91 All Stars"},
    {"spotify_id": "6CZr9MXuLgVw8tcZxrf29Z", "name": "joysad"},
    {"spotify_id": "6WK6ZRBhoIRXA8xkAvhMKv", "name": "Maxence"},
    {"spotify_id": "1MBqzcu6aiY7GzP5BfG56T", "name": "La Caution"},
    {"spotify_id": "1QHLcqY9m9aoKWcjBiQV0y", "name": "Di-Meh"},
    {"spotify_id": "5rtvBFj4IeWDwKjf9cmeKv", "name": "GS"},
    {"spotify_id": "30CSER9MSe5LNqFtdFkIm8", "name": "Pxrselow"},
    {"spotify_id": "2CgPBdrhhS17cwVDnnq7Up", "name": "The Shin Sekaï"},
    {"spotify_id": "2v6hsrO3H2uRWgdsPfGQ1d", "name": "JMK$"},
    {"spotify_id": "64ajvIvaxJSmdwLGW0IJBo", "name": "N'seven7"},
    {"spotify_id": "4NYN8zAaPqtfM9MHFTmC0a", "name": "Mayo"},
    {"spotify_id": "33v1e0a3iVU2BBzW3orMrN", "name": "HAKAI"},
    {"spotify_id": "3wc57nV2fGEoM8x4xPK1O9", "name": "Dixon"},
    {"spotify_id": "1k0mwo8CyFp0ZlAGcu4LA7", "name": "Dj Weedim"},
    {"spotify_id": "5Jh4UFOCWwleD3kcd88xyh", "name": "Fabe"},
    {"spotify_id": "0lMsSW9R8prEif6Q3aVnEH", "name": "Zach Zoya"},
    {"spotify_id": "43mlbNLGRuLXwqTE8G61JB", "name": "Lyonzon"},
    {"spotify_id": "5QWxhSb2qupA3pNE3X6VpM", "name": "Lord Kossity"},
    {"spotify_id": "7MqaRBgnaFIndVIYwC43AP", "name": "Swift Guad"},
    {"spotify_id": "4PlMVWxO3DGtAvMwbXgctQ", "name": "Le Club"},
    {"spotify_id": "3nul4CdUXaaA3QSHrduvtu", "name": "Esteban"},
    {"spotify_id": "5NsZZCV8VpunXmJ2cIohci", "name": "Versor"},
    {"spotify_id": "4kz8Ax2USW4Xae9WSQHVec", "name": "Hunter"},
    {"spotify_id": "1cRhxmFvL3Ef4vx4jSCy04", "name": "Mafia K'1 Fry"},
    {"spotify_id": "6EFWFj8GbksweYxSkRkJFe", "name": "Leck"},
    {"spotify_id": "3OBjXOhx80RvmHyUEMNs2F", "name": "Hache-P"},
    {"spotify_id": "1r8lodN1CqZ2BXsJd51aGm", "name": "Carbozo"},
    {"spotify_id": "3r7t38zbphQtpfAH12UbRd", "name": "Makala"},
    {"spotify_id": "41yZRhcJMRMFWihPbLxGkM", "name": "Senyss"},
    {"spotify_id": "5Bg2PFMIG6oqToVIATnZsd", "name": "Kosei"},
    {"spotify_id": "0ATaMBIaHwtM6LZpQam5r2", "name": "8ruki"},
    {"spotify_id": "47cHAE0NFwzGOlc3L4oszT", "name": "Enima"},
    {"spotify_id": "6J434ZmyHxFcBjHXAZL9QY", "name": "Kacem Wapalek"},
    {"spotify_id": "58lWi9l7zeTHdUz6Glzm9p", "name": "Junior Bvndo"},
    {"spotify_id": "0DQx7HJhLzjbSQNsNhrpLT", "name": "Leith"},
    {"spotify_id": "6oc3ElPTqRlMxSWCuZPi3x", "name": "Kool Shen"},
    {"spotify_id": "5E62kscxqQ6HRcRRsxm1n1", "name": "Moubarak"},
    {"spotify_id": "0ajjnGmVt2aVGD70lDbVl6", "name": "Sicario"},
    {"spotify_id": "0N97AyCm8eLH5cE59BvSUm", "name": "Cikey"},
    {"spotify_id": "4ZPLdCBeYJBAjsLTWRcZEs", "name": "Emkal"},
    {"spotify_id": "1KTf3AtEB3A96IfHv2kzPh", "name": "3010"},
    {"spotify_id": "6cL4mIBIA85TnOIzhhukZT", "name": "Tissmey"},
    {"spotify_id": "4Bb3vJgKsgjMmxDEElLZ1Y", "name": "Josué"},
    {"spotify_id": "53loJtHWjCG1TyKarW2mzk", "name": "Benash"},
    {"spotify_id": "3igykO7sW43wfhSjvnETTo", "name": "Prototype"},
    {"spotify_id": "59q5EZU92LcdN88k9rh3ek", "name": "Team BS"},
    {"spotify_id": "4EfDnNKz2dl0KND2oQB3Cc", "name": "Volts Face"},
    {"spotify_id": "3JudvZnY94AkCzfAVXzawN", "name": "Slimka"},
    {"spotify_id": "5N2P9zB8202SrtnWCjqe1j", "name": "thaHomey"},
    {"spotify_id": "6ekcMUMZoiX2HBbQGZgNh1", "name": "Souldia"},
    {"spotify_id": "0mmk05vTtGGG2jYwLxRHwy", "name": "Zed"},
    {"spotify_id": "5q3WViYe7mEvzU9CY6lixh", "name": "JoeyStarr"},
    {"spotify_id": "5p9kx3T4qpQIq88fibnUeN", "name": "Haroun"},
    {"spotify_id": "0TZ8Slkdu2G6nobZiDsNEj", "name": "Hubert Lenoir"},
    {"spotify_id": "3I2ayKNkuX0gqKPZDBnxNk", "name": "Dibson"},
    {"spotify_id": "6NBA1GBrRG7fxTPDjKwFxm", "name": "Nusky"},
    {"spotify_id": "6vDYFCXQbWPqlUEyBaVbMW", "name": "Stomy Bugsy"},
    {"spotify_id": "34dSaKok3USBivMGTmIlXx", "name": "PSO THUG"},
    {"spotify_id": "5nzb4lFHogGWcsd9njLT0M", "name": "Barack Adama"},
    {"spotify_id": "2IYkVgw5hAfAgxWPY0KgUI", "name": "Chaman"},
    {"spotify_id": "1oabIvG8mrqtx1uaRrOyPd", "name": "Take a Mic"},
    {"spotify_id": "2j93xBBtZnS9YJGJUcWHwg", "name": "Stavo"},
    {"spotify_id": "0UeKDbiaApyP7qKfcmGN03", "name": "Lesram"},
    {"spotify_id": "5oM4ylX9mgzyzDD6yYPUal", "name": "Dehmo"},
    {"spotify_id": "12fU2Tyt3TEQn0bjNS0kzC", "name": "L'Skadrille"},
    {"spotify_id": "526SiOeohcxxzAqB1JCuQb", "name": "Jimmy Whoo"},
    {"spotify_id": "6G2XHZtd6wJhEHtipzcpqy", "name": "93 Empire"},
    {"spotify_id": "1h9TsJVZdaubBn1BZHaAhk", "name": "Jnr Slice"},
    {"spotify_id": "3Ii7kCftek6SPKPEZx3GYE", "name": "La Famax"},
    {"spotify_id": "0rIcS71BzqNgTQl8yjiprz", "name": "Chanceko"},
    {"spotify_id": "2uuaoYjn1Pk0Y3NOyMR0KR", "name": "Zoxea"},
    {"spotify_id": "2HXioEvQuzCcNmRsImBTET", "name": "7 Jaws"},
    {"spotify_id": "7CayiktXZ1bRAkG9qGsctx", "name": "Eye's Berg"},
    {"spotify_id": "5xMkiuMCSS13z5shShg7Mz", "name": "404Billy"},
    {"spotify_id": "2q8BTMaWesmxIXCB817C9I", "name": "Aladin 135"},
    {"spotify_id": "4IAqcSIINRfPQC57mgYhW2", "name": "BRVMSOO"},
    {"spotify_id": "4NKumVnSozo1F50Wji9ddY", "name": "Alpha 5.20"},
    {"spotify_id": "4B5Y9RoKzJpDmHsZKQf0UI", "name": "Leonis"},
    {"spotify_id": "3Mo6O9iqKSw3Mn6v5zZfEy", "name": "Ärsenik"},
    {"spotify_id": "22VOejB8RaATr9yhodu6U3", "name": "Chicaille Argenté"},
    {"spotify_id": "6ENue1D9ypy32vI8BWQx33", "name": "Bakari"},
    {"spotify_id": "0rqQfmTWtmxzlrNmnruQXS", "name": "Khali"},
    {"spotify_id": "4s7lub6OTMblNwFn9wXClR", "name": "Maska"},
    {"spotify_id": "7m3gqqtxB5FGXBFmOkR8Sf", "name": "Ratu$"},
    {"spotify_id": "3nRUvKHrGi4lrRF01yTzod", "name": "Don Choa"},
    {"spotify_id": "0wJDbxpqtwjA2FxfU6KI0E", "name": "Max Landry"},
    {"spotify_id": "7M2ZGRhAsmh4On0JlVEyCX", "name": "Madrane"},
    {"spotify_id": "58lTtz2gYYzeaIVYNGisdr", "name": "Leeroy"},
    {"spotify_id": "5MyafTxCvKDZVVALZUByV3", "name": "Lim"},
    {"spotify_id": "7prKK2GchmQEkgUsAFXEz0", "name": "Dada"},
    {"spotify_id": "3iE3iLBiJ4SVgNqa6JASfY", "name": "Lino"},
    {"spotify_id": "3dQBVcyYyooIelAojy1CmQ", "name": "Azur"},
    {"spotify_id": "3HB9D7hdRBWUUnHWltSHlr", "name": "Esso Luxueux"},
    {"spotify_id": "1eDFNPc0Y0eMbG03c89Dmw", "name": "Busta Flex"},
    {"spotify_id": "72TdCQUBRXtFFrbNtx3p8J", "name": "Fixpen Sill"},
    {"spotify_id": "4yDo1iZ02sOpLsh1oGAAg9", "name": "Seth Sad"},
    {"spotify_id": "5x8YMWd2tIBdDzuIJM6WFi", "name": "Mystik"},
    {"spotify_id": "5Gf71JW8QjF77ELQ94JX38", "name": "Pit Baccardi"},
    {"spotify_id": "2W2NUrosOnwAI1hZIVbwit", "name": "nelick"},
    {"spotify_id": "3iNKvp2muYK7EOJvjjjNIy", "name": "Dirtyiceboyz"},
    {"spotify_id": "0AFEmxYJqHfNUtADd6eWhc", "name": "Kamini"},
    {"spotify_id": "456GKlKmVdzrsmUDmF0Xug", "name": "Hippocampe Fou"},
    {"spotify_id": "3xEtgUoHv1k1JyqYLEwRGl", "name": "Luni"},
    {"spotify_id": "2QaL4Mj0beDXYBJuer1TUe", "name": "Mac Kregor"},
    {"spotify_id": "31Gbv2WFzy6QX0X6DkGiHA", "name": "Benny Adam"},
    {"spotify_id": "17o6H1EQGD90TQxJ4pErIU", "name": "Varnish La Piscine"},
    {"spotify_id": "4XCcYzu2zRJvBp3QZct3Oj", "name": "Medi Meyz"},
    {"spotify_id": "6162ZDzd0LT28Lxdj52jjK", "name": "Sheldon"},
    {"spotify_id": "3gYoYSbWPhxA0zY9lZ4Ldv", "name": "twinsmatic"},
    {"spotify_id": "7pm7WxKYyWWWY2PI6VO15d", "name": "D.ACE"},
    {"spotify_id": "0zw74GbIgk0thLlMGeQV2H", "name": "Dadinho"},
    {"spotify_id": "7rjdQx7OSfthvdWWgSM1e5", "name": "Gouap RTTCLAN"},
    {"spotify_id": "6pS2QdnuxFtcbLxQqe8DN6", "name": "Kamelancien"},
    {"spotify_id": "5gdrTDqKDcfO1Dkc5a9ppZ", "name": "Sultan"},
    {"spotify_id": "0P8O2tgFwGDTSauprJthJI", "name": "Sango"},
    {"spotify_id": "3XQLSTYyBneA9vzOEP9OSH", "name": "Doks"},
    {"spotify_id": "1H8n1TwWuDJGP6BS5R3nsU", "name": "Zefor"},
    {"spotify_id": "3uklrkyCGBBg5PoFTbEoim", "name": "MoKenStef"},
    {"spotify_id": "2RnUvL40zj7eruqfVNP3D6", "name": "Leo Roi"},
    {"spotify_id": "4A1BIRTQQ1yNPwcg57Ubq7", "name": "Haristone"},
    {"spotify_id": "0enzx5Bq2F7Rq5BN9kWXJl", "name": "James Baker"},
    {"spotify_id": "39dsykDOsgbhSWe39v4XC9", "name": "Todd"},
    {"spotify_id": "12SPMb4VM4PyBD9no01jbH", "name": "Seven Binks"},
    {"spotify_id": "6wUGiWb7FR3Cv39sELlp1U", "name": "Kasper 939"},
    {"spotify_id": "0et1mZYLCSVBIBUY94B8Xn", "name": "Sokuu"},
    {"spotify_id": "7Iw6TwPkS7bja1OrA3Neal", "name": "2zer"},
    {"spotify_id": "5kKxz4PDHgrpIt8LX3PPiF", "name": "Jayel"},
    {"spotify_id": "0BJ0xV9DSgkLNhImM5qPen", "name": "Enfantdepauvres"},
    {"spotify_id": "2RPfjjkSe3N9gmyGk1ZBxo", "name": "Senamo"},
    {"spotify_id": "3kBOfwS7wKdNH41Zy8eJjx", "name": "Vin's"},
    {"spotify_id": "0yR7nCYOs6Fdj0SAk4L4zC", "name": "1minute2rap"},
    {"spotify_id": "4ysSjuzCs1kAh2crzzJxR7", "name": "MAPESS"},
    {"spotify_id": "58gEwrkV31Abu5PQvSPgh2", "name": "VEUST"},
    {"spotify_id": "0FO41jGlT3izLX7oULFUlr", "name": "Chinwvr"},
    {"spotify_id": "6neEhK0FxJha78nD9giAjW", "name": "Mike Shabb"},
    {"spotify_id": "5qMf7CFNNQi7gb1WQb74Pc", "name": "Rowjay"},
    {"spotify_id": "3dARbB5oGnzJMklK69pwxh", "name": "Lestin"},
    {"spotify_id": "0VbfTzGkMlei0XtibnO466", "name": "USKY"},
    {"spotify_id": "1nDtmYJmQcZEXU56pz5R9d", "name": "Jozii"},
    {"spotify_id": "2v1aABncTZrtkXA84ZqtyU", "name": "MB"},
    {"spotify_id": "3i3yb6Daaf3z6OLKvMFqlK", "name": "CG6"},
    {"spotify_id": "5uo0xw2Agih4NcDVajOd6e", "name": "DMS"},
    {"spotify_id": "2BAG03enVzZgv9Tb2hqImG", "name": "ALP"},
    {"spotify_id": "4Ahw76UVS2GoBsByIdRjQt", "name": "Pins & Dimeh"},
    {"spotify_id": "73Ifh3j4V2PI6R5JNkcIyz", "name": "robdbloc"},
    {"spotify_id": "1rBnd8KxDndiiiIyjOsFtw", "name": "Dika"},
    {"spotify_id": "6NxJhQxcEAxCdfxXt4ScMt", "name": "Unité"},
    {"spotify_id": "7l6m2BySHwnjJuw22SXwh5", "name": "Limsa d'Aulnay"},
    {"spotify_id": "0OS83mLy4bVAE3tyNB5myI", "name": "Krilino"},
    {"spotify_id": "3qbqyAhAkU804siT3gPzK5", "name": "KRN"},
    {"spotify_id": "7g9QCyx9r1R424eMqNtM2g", "name": "Kheops"},
    {"spotify_id": "4Rc4ZjE8dK1b794tfc3BIt", "name": "TESSÆ"},
    {"spotify_id": "6xrmcNsyd2topX3r1suglc", "name": "Dr. Beriz"},
    {"spotify_id": "0eFmnuvX7ZDCsnOesNifzb", "name": "Neaj"},
    {"spotify_id": "1NKxtmaJSl8sNwCwAhNbdl", "name": "Lemon Haze"},
    {"spotify_id": "0YjLBTzWfiNLqIseRzCa5e", "name": "Hologram Lo'"},
    {"spotify_id": "6DTpmzMa0Gz93kRKUo4JfQ", "name": "Elh Kmer"},
    {"spotify_id": "7hk0d1oKXetQy9G7YUienU", "name": "Michel"},
    {"spotify_id": "5HdWyNYybG0xZOdJOShrd6", "name": "Trafiquinte"},
    {"spotify_id": "4ME56PlDfT9QKf6sGcRgPm", "name": "Wit."},
    {"spotify_id": "3MLibxmnYlJEtSLG4s6XvC", "name": "Le A"},
    {"spotify_id": "56sq0vXlZmTpjbEReOfhMX", "name": "Geeeko"},
    {"spotify_id": "1lhFyyRRWH7llPdQGIhXYD", "name": "83HADES"},
    {"spotify_id": "1g4gTYnPjQSIOAzFU3V8AL", "name": "Youri"},
    {"spotify_id": "5BZQ1LKKtw3uu6NIJdlU4Y", "name": "Chanje"},
    {"spotify_id": "7CxSejERLJhkuYRU6D1d8C", "name": "sean"},
    {"spotify_id": "3EwKGrg1Y5dAF8frDO6mLS", "name": "LMB"},
    {"spotify_id": "52CEzAtIDEJInO8yL0blFB", "name": "Jäde"},
    {"spotify_id": "11VqEMsX1gln47ik7tS9fc", "name": "La Smala"},
    {"spotify_id": "20YBOyvKkIXm0gpMI1cVbN", "name": "VTEN"},
    {"spotify_id": "4nOixYyTN15ZSzPSna2Oah", "name": "ATK"},
    {"spotify_id": "7lR8WBYvyK9iTHuv5HwUpe", "name": "Dr. Yaro & La Folie"},
    {"spotify_id": "6Q2GjyK0uIN62HJM1CCo8v", "name": "Set&Match"},
    {"spotify_id": "6XqX8hSumPdlITIh7EHnHt", "name": "Guirri Mafia"},
    {"spotify_id": "6Dth9R5WxjhtfVjh4j0iMM", "name": "Deadi"},
    {"spotify_id": "7siKy5Wrq7TwvyJ21KushJ", "name": "Saturn Citizen"},
    {"spotify_id": "3lcaxkgcJetq348VioG0s6", "name": "S-Pion"},
    {"spotify_id": "1g6Hs3pSerBl61R9AKUeHr", "name": "Kepler"},
    {"spotify_id": "16vfg5F2MKku9FMIrFIqry", "name": "Q.E Favelas"},
    {"spotify_id": "7u4o1K3Qui9DmeWqSMsa6l", "name": "Peet"},
    {"spotify_id": "2ZYYyHcrFrohSQolgBytnm", "name": "34A"},
    {"spotify_id": "08pIDlFQfxL4YPyWrJ05Hb", "name": "SIMONY"},
    {"spotify_id": "1IwYT0LssMMf3aprn3pRzv", "name": "Rapi Sati"},
    {"spotify_id": "1nzsygZNqmL6J2CLFcFN46", "name": "Retro X"},
    {"spotify_id": "0i1E3djBqQVu6R61byWo3y", "name": "Squadra"},
    {"spotify_id": "4TcpaHeYWjPltfzyTN76Ct", "name": "Wall.E"},
    {"spotify_id": "2oOAiE62UgqjCEWTHPdn0F", "name": "Nuit Incolore"},
    {"spotify_id": "47NHcwh7V1kVlxr9Co6k1r", "name": "La Clinique"},
    {"spotify_id": "4dZzpakTDlQy33Iwvf3reB", "name": "SKG"},
    {"spotify_id": "0wbdRQZMz6OiGgoMfkgne9", "name": "Tengo John"},
    {"spotify_id": "28iAsy77mBm7rk8K9cfFvL", "name": "Biffty"},
    {"spotify_id": "6XJmHR6Q8lIpjx2JukLaQo", "name": "Demon One"},
    {"spotify_id": "3VTjgKLiBLDXWCigMpjFan", "name": "L'As"},
    {"spotify_id": "1syRCcHBM3LCOSLorQU0YB", "name": "VSO"},
    {"spotify_id": "3OOojNFDlThXjpGkztq9gT", "name": "Toma"},
    {"spotify_id": "6COtnkYhmRVdsDXhSGYtBO", "name": "C.O.R"},
    {"spotify_id": "0SVNXV6d5r6CpBCpe8Fbhf", "name": "Canardo"},
    {"spotify_id": "6eZmUcps7ec36kCUw0LLWw", "name": "Savage Toddy"},
    {"spotify_id": "7jAs3bSFCCU88rzme8E9fz", "name": "Imposs"},
    {"spotify_id": "5O5o8ORa6JnUInvOUmmvft", "name": "Kobo"},
    {"spotify_id": "3Vg40047qXc3ZAqMu3GUSO", "name": "LAZZIO"},
    {"spotify_id": "2EG7EcOjclRyBRTWra1jcG", "name": "Louis Aoda"},
    {"spotify_id": "4INwdDeRpzMrpL6HcGTvYD", "name": "Juice"},
    {"spotify_id": "5WJGVVWdW0OiMJV4pEv1oD", "name": "Larsé"},
    {"spotify_id": "45EiqrrOPCklyjQWF3Z6pR", "name": "Coelho"},
    {"spotify_id": "70GOdbV3l3bRrYkRhsgDvY", "name": "SONBEST"},
    {"spotify_id": "3Gcn7eKPiTv6jwqoyIhVMO", "name": "Mous-K"},
    {"spotify_id": "3zAlF5gQNQo3Cwv8uQu5aG", "name": "K-Reen"},
    {"spotify_id": "5Y3HBYsky3RyPqIDMP2wvt", "name": "Seezy"},
    {"spotify_id": "3Op4g1wmQJxGTmeFSQ8z52", "name": "B.B. Jacques"},
    {"spotify_id": "2AD97sdXTycPyTc9rHN2s2", "name": "Abou Tall"},
    {"spotify_id": "2roV5f30gWneIOkPjdpntN", "name": "Lorage"},
    {"spotify_id": "69yVEiGKjokl3qx25AbBPs", "name": "Ol Kainry"},
    {"spotify_id": "5K44yuP8WLPHoyvXNXOtED", "name": "Bash"},
    {"spotify_id": "3dN1EUAKOFCUBPFXRUdqKu", "name": "Rymz"},
    {"spotify_id": "1mAdVbvz1w6v9I5iGxRtnE", "name": "Yanso"},
    {"spotify_id": "4TuSbcM9N0XoSrJDj06qtg", "name": "Saamou Skuu"},
    {"spotify_id": "5oWCZVOBaS8Bn3JW6Wy4cn", "name": "Mussy"},
    {"spotify_id": "7yz7tVF8i1Jr6roiq5CUuD", "name": "Rocca"},
    {"spotify_id": "0kcFJUUSenAq7PbxDk7Ek9", "name": "Blacko"},
    {"spotify_id": "0HXr8umdyGHb2aXClWD1k7", "name": "Gueule d'Ange"},
    {"spotify_id": "6Twdw4cy4bu2vRXuCne8uU", "name": "Asakura"},
    {"spotify_id": "2VXsRo1aTjdh4KydrrKtF2", "name": "Grems"},
    {"spotify_id": "6Mi73JugAPIs069hJzI0rI", "name": "Jeune Loup"},
    {"spotify_id": "2Rs9OXF7KV8QXIzg7hT1mv", "name": "Faf Larage"},
    {"spotify_id": "0u8fuhFdG3E8WKsqQXy63B", "name": "X-Men"},
    {"spotify_id": "0U4UrgHYuU5CiuJoMZf4fl", "name": "Falcko"},
    {"spotify_id": "0uRneTUgP2kyaFBDWmALuW", "name": "Euphonik"},
    {"spotify_id": "082dnQ2APdm4cFw8eILB4u", "name": "Lacraps"},
    {"spotify_id": "6yfcoVGojS0XOgw8dVAb0R", "name": "Hipo"},
    {"spotify_id": "6B535quc1yWnDhnBMCvosY", "name": "Mokobé"},
    {"spotify_id": "10Zy7pPIFESaB4olenUcfD", "name": "Moka Boka"},
    {"spotify_id": "5EHFGV0DMEet7QHdx0M1D6", "name": "Jarod"},
    {"spotify_id": "4UUv9SzL15YuB6epX0YGdy", "name": "Le 3ème Oeil"},
    {"spotify_id": "4X4SnYGgU68gRnuuHzBTdY", "name": "Le Gouffre"},
    {"spotify_id": "36y3f2GpxgEkUqsym5tpK1", "name": "Le chroniqueur sale"},
    {"spotify_id": "6LAeGs6PiBDev5KdMdbRY3", "name": "Zinée"},
    {"spotify_id": "2OycTEXMkHcR33DNZ3BpVJ", "name": "GR OMEGA"},
    {"spotify_id": "0NAWq4CW7DxGwgIm1Ock5C", "name": "Tizzo"},
    {"spotify_id": "6lh7vDO9GPAbyQ7PhT2a80", "name": "winnterzuko"},
    {"spotify_id": "5vUkpDxDVZIggZLIdDKTNN", "name": "Kayliah"},
    {"spotify_id": "5OiICeeNubhIo750yEeYKk", "name": "Freeman"},
    {"spotify_id": "2Xlv4GthvDhwSRVJ7mdSIa", "name": "Leone"},
    {"spotify_id": "5crOTgkcDtgMTCoatASEBs", "name": "i300"},
    {"spotify_id": "4gD7pjkmrDtA85YBMkg5GA", "name": "Kamnouze"},
    {"spotify_id": "3tKR0XXN0pW0Kl7UDAVSHL", "name": "Brasco"},
    {"spotify_id": "0gnvHfvVVSQ7xcTVFC5TJk", "name": "R.E.D.K."},
    {"spotify_id": "6dCubgboW2yqxg5cnveToX", "name": "Monsieur Nov"},
    {"spotify_id": "1IEmy7NUSGRZijdZoJe90C", "name": "Le 77"},
    {"spotify_id": "4cmRb0sfE6QnlINaOtn35M", "name": "Keusty"},
    {"spotify_id": "6qQ2if1od4FAg6ilAETwMG", "name": "Alaclair Ensemble"},
    {"spotify_id": "6hjoQ84QiA6LVscW9dhcmO", "name": "Tedax Max"},
    {"spotify_id": "1lQGUDU6ioEc0j9dWQARbY", "name": "Mothas la Mascarade"},
    {"spotify_id": "2RdmK6Xj7HFPuY6JyCSG26", "name": "Arco"},
    {"spotify_id": "6pg4S5KTCPiEBp0rSWsaI6", "name": "HMZ"},
    {"spotify_id": "4hLEWmW8SCJYxZkWfSJakZ", "name": "Eta"},
    {"spotify_id": "3xzfeAKY5GlsHo4uQevDu0", "name": "Manon Clément"},
    {"spotify_id": "0JAbmlSLQqD6DAw2d8jdvz", "name": "Dany Dan"},
    {"spotify_id": "76xhXA0WSzUzUzwMYkGhEW", "name": "Bilel"},
    {"spotify_id": "3e8WCsuzumIFZRbOYFsfim", "name": "One Shot"},
    {"spotify_id": "0QODQ4TiVsOcGvWxk97Ylv", "name": "Calbo"},
    {"spotify_id": "5OeY6e62St2Nubj9hbfuIb", "name": "Bilton"},
    {"spotify_id": "2bZUYQoqYg8Wh7SNjbYIL2", "name": "Mazoo"},
    {"spotify_id": "0qNrNX9FKJM0ZJFbcbMlMp", "name": "Shreez"},
    {"spotify_id": "4vbxtxqdkeHt1dICi63qs8", "name": "Jwles"},
    {"spotify_id": "2uNTCtTH48JmBT5b3PEgcW", "name": "Lucio Bukowski"},
    {"spotify_id": "6knHYSqYjjguJjD5SvjrLx", "name": "Ideal J"},
    {"spotify_id": "0bLmm8afVAt8Vb5nhPsx1B", "name": "XV"},
    {"spotify_id": "1KjAOiizQyW4rpuWE5fjTx", "name": "OGB"},
    {"spotify_id": "5n8f4D4E0gNe8P7A9efo4v", "name": "Jolly"},
    {"spotify_id": "6RcPiWIVptnyi8y3EIbDLB", "name": "Blu Samu"},
    {"spotify_id": "0wNPt95tKAlBygX040Zi0V", "name": "KDD"},
    {"spotify_id": "0uziZOQoq7GATTdJqMOX5s", "name": "L'entourage"},
    {"spotify_id": "5TwGksCe3pSfpBcV96k6sS", "name": "Melan"},
    {"spotify_id": "0ey1YK5NTXjrf0adsXFsTw", "name": "Bitsu"},
    {"spotify_id": "33X1P8QyvcOhswkaFv06ss", "name": "Zeeph"},
    {"spotify_id": "1LVM8ye1ivMW71OmS264u2", "name": "Théodore"},
    {"spotify_id": "0NRTlhytRhIj2SgzLqs9lP", "name": "Seyté"},
    {"spotify_id": "1uzx1lyRA2RIZlVSxOfBAi", "name": "Souffrance"},
    {"spotify_id": "0Eh3yFYMU0c1sBsmlG0Ulj", "name": "TSR Crew"},
    {"spotify_id": "74tb4BL2gQ28BJicVAWsdb", "name": "LES ANTICIPATEURS"},
    {"spotify_id": "3qgMGg3EPBxUtdPOGAUKJF", "name": "MOH"},
    {"spotify_id": "6IjtuYp9QWhZbWaddsGQ7y", "name": "Vaï"},
    {"spotify_id": "3xQSe5wUqOUFcF5GWlziQb", "name": "Tsune"},
    {"spotify_id": "2rX5le9Bn1XdQwPsXA8aPP", "name": "Sally"},
    {"spotify_id": "4dQxvm7YD9qOd3SdToppT8", "name": "Kiff No Beat"},
    {"spotify_id": "09eIkj0LtF1nbqTj9TBxGr", "name": "LeGhost"},
    {"spotify_id": "4LujPNfyrtunY5noju2iIa", "name": "Furax Barbarossa"},
    {"spotify_id": "3IwGtEVQB7RxflqPCwnkO2", "name": "Tony Parker"},
    {"spotify_id": "1z0j1VhCO5qUbM6vxmEMDB", "name": "Flynt"},
    {"spotify_id": "3taeGwG1yqKJQvpgh21E4j", "name": "TTC"},
    {"spotify_id": "0kTTkHvvtYNtRKnRPyNGhT", "name": "Titai"},
    {"spotify_id": "7kFoHyLeI8IWSoKZ8uIeY1", "name": "Suikon Blaz AD"},
    {"spotify_id": "3yoDs6sqTCOYJXa8T7LGmb", "name": "Your.Nash"},
    {"spotify_id": "4bQKPhS0pAXWAoaQ8Q9bpO", "name": "Oster Lapwass"},
    {"spotify_id": "1badJ5qBBvLuJ6qRqkRtR7", "name": "Primero"},
    {"spotify_id": "5qAHb2rKTK9bWXF70QvPQn", "name": "Alibi Montana"},
    {"spotify_id": "5ww4TnrPAbSUOE0kvRjuoB", "name": "Dinero"},
    {"spotify_id": "2WsjdLBMblY2Fzgs1yMRW6", "name": "Yannou JR"},
    {"spotify_id": "6dPiR2ZnRODP7s8WFrL1WB", "name": "Mini RTTCLAN"},
    {"spotify_id": "7fy5E9AjeDhMSbVKrOGk55", "name": "Mafia Spartiate"},
    {"spotify_id": "26WTl77DrAt9IDNihQmZMW", "name": "Big Red"},
    {"spotify_id": "0dsrPInY7xTkhmjJIUc7ZT", "name": "5 Majeur"},
    {"spotify_id": "5cHEMXrGvrs8I6iYWNwTkh", "name": "Les Sages Poètes de la rue"},
    {"spotify_id": "47BEXrGacbFC66aygrjSxJ", "name": "La Peee"},
    {"spotify_id": "2juymGEgJZTvtxOcnCWY17", "name": "Serane"},
    {"spotify_id": "3GqXhHDrrNK9J2P1D9ZUr5", "name": "Kader Diaby 4Real"},
    {"spotify_id": "2yRhS7HafDp8QUAjiIsofx", "name": "Kodes"},
    {"spotify_id": "79aJFSNTYQQclXUhI06uWI", "name": "Roseboy666"},
    {"spotify_id": "7Bc4N4SWkPWM9TipAmwj6q", "name": "Youssef Swatt's"},
    {"spotify_id": "2flTkRWXExICi9z6DFL2nf", "name": "Ismo Z17"},
    {"spotify_id": "1UILCk5p48n9qaNf1uie0a", "name": "Tuerie"},
    {"spotify_id": "5yhoElw9gCKKsOAK1mmgHJ", "name": "DawaMafia"},
    {"spotify_id": "098i6pLeCCtxPtXvmRmacI", "name": "Hiba"},
    {"spotify_id": "27LbkIauxECwrPlkcG4tFs", "name": "Djalito"},
    {"spotify_id": "10puYSSj5YS2rMO7euRJ85", "name": "Slkrack"},
    {"spotify_id": "27CfqXC2gCyrSyUaHN01kO", "name": "Cianboy"},
    {"spotify_id": "3VxFXCMe9fR5v75N4HTZ0q", "name": "RAS"},
    {"spotify_id": "3NQnos2tL93u0rTCCkhwy5", "name": "Volodia"},
    {"spotify_id": "1MXjeAvBQlC8bKcqGpqtL1", "name": "Milk Coffee & Sugar"},
    {"spotify_id": "70ygaPJzebQpSKtzbW2u93", "name": "I.K (TLF)"},
    {"spotify_id": "3bOlMjhZuCsFt1dKkPCGAK", "name": "Nadjee"},
    {"spotify_id": "5KkR5YdE0YnQKtmrjDgZfH", "name": "Holy Kidd"},
    {"spotify_id": "2I1RlqUoxGwDGGe5WuyCPQ", "name": "Black Jack OBS"},
    {"spotify_id": "4FZdtzXycKH3gwStYJrx18", "name": "Abd Al Malik"},
    {"spotify_id": "7ztNNzgtrVd1rj5R4owjNb", "name": "Panama Bende"},
    {"spotify_id": "0hEUHT3c8Hj6wlefq6iPS1", "name": "88KVLY"},
    {"spotify_id": "6uQLXI6jetBSHf1NFXpAV0", "name": "projet facteur x²"},
    {"spotify_id": "42SznvyZNQon11BUfdPadN", "name": "Fils Cara"},
    {"spotify_id": "0NuAhoKXhbTZEQwKzvVYRm", "name": "LauCarré"},
    {"spotify_id": "0g5iQz7W3rnBbGOdW8ZnNH", "name": "K.S.A"},
    {"spotify_id": "6C91nXJJkhPEoc5thhKiNn", "name": "Boumso"},
    {"spotify_id": "4KopSPzxYX2YfExvXefbjp", "name": "cityboymoe"},
    {"spotify_id": "370MMDdlD2IyUWyT1bfuq5", "name": "Soklak"},
    {"spotify_id": "3bG1qrusG1VEw4bPPQwSA7", "name": "Kazkami"},
    {"spotify_id": "20JMfmzDb5cjHxEoMXXMyY", "name": "Favé"},
    {"spotify_id": "4lL9nnu7FX1Qp2oBbQZklz", "name": "Ixzo"},
    {"spotify_id": "0dT6c6YrbVHStlEuj8NsbN", "name": "Svinkels"},
    {"spotify_id": "6X87X3dp4pzPM6B3ZmkA3v", "name": "Yuri Online"},
    {"spotify_id": "3y2HuzAEauV9QXE9cFJpIv", "name": "La Cliqua"},
    {"spotify_id": "4QI3nIR2qo45wwFeYYBc8r", "name": "Nos"},
    {"spotify_id": "0KmSqHKu9V4ZvexLyQiS5X", "name": "La Brigade"},
    {"spotify_id": "500IcTDu7sWtvgvEZSIiFE", "name": "Aketo"},
    {"spotify_id": "7tm8TKV0OowlpV9QyUxhr1", "name": "Eden Dillinger"},
    {"spotify_id": "6qEjzPkbaqYAKt4MiO0CY6", "name": "Walid"},
    {"spotify_id": "1iUs8M4cOSGdwH8c6uIzFn", "name": "ZDRID FAMILY"},
    {"spotify_id": "2kVtWHg7vhLehbhWW0ZZhZ", "name": "Mino"},
    {"spotify_id": "39DAWghKRMpF6aKbD3yZqU", "name": "AP du 113"},
    {"spotify_id": "5H95sNW22U0VkC8v7qk9FI", "name": "Zesau"},
    {"spotify_id": "5S20kfnvfovpK5ncgaDkWU", "name": "Jorrdee"},
    {"spotify_id": "6SKhOW2FPSCPBCSTXTS6Fn", "name": "Comar"},
    {"spotify_id": "0CA8jbz5CnyVRLR807BskD", "name": "AMIN"},
    {"spotify_id": "7yHWMjHKT8Y5k2gTYfVqW0", "name": "Matou"},
    {"spotify_id": "0glTknFjdHbcQ96GgYFC7U", "name": "1863"},
    {"spotify_id": "6YPGhj88VOEmQ6e9qTotvA", "name": "Golgoth"},
    {"spotify_id": "7cVhbi4q498qnpR64Cwr2y", "name": "Jeunesaint"},
    {"spotify_id": "01vun3lwrSoQ478gOotOe6", "name": "Ministère A.M.E.R."},
    {"spotify_id": "1oqGbRIGyWZm1SaIkDlatw", "name": "Noma Rttclan"},
    {"spotify_id": "7icPanI4wjZVQCkvaUMWLX", "name": "Sarahmée"},
    {"spotify_id": "395spUELWr54gJKYr3EE0I", "name": "SAÏK"},
    {"spotify_id": "2dzYZkJWPElSGPcz4ofcDA", "name": "Yassin"},
    {"spotify_id": "4Lc100wJvtsyzNuPICliGy", "name": "Prince Waly"},
    {"spotify_id": "7r35uLFg5fJcsLe60AdWhK", "name": "As"},
    {"spotify_id": "37060l8iXQAWuFo1g3RCQ6", "name": "rad cartier"},
    {"spotify_id": "1JEYKq5j5ibaa9MS9C0T7z", "name": "Dragon Davy"},
    {"spotify_id": "2TNEke8iPCbFBj8Tp9KlnJ", "name": "David Okit"},
    {"spotify_id": "5xwkZR4IElUHC9y1Yu23mE", "name": "Sysa"},
    {"spotify_id": "0sX9shkpi9yYK65nZCeeiW", "name": "La Rumeur"},
    {"spotify_id": "2EOkrbSLspAmnLDvqtgJlj", "name": "Beamer"},
    {"spotify_id": "3FX25sj0KYV6VNFlMDRZxo", "name": "Loveni"},
    {"spotify_id": "1jlwPYUQdkh74aHWRHa7hF", "name": "Bisso na Bisso"},
    {"spotify_id": "72LKZ9aKqt1xHie4UMKElg", "name": "TNS"},
    {"spotify_id": "7MNu4r2wgx8eDWfN1hdbTe", "name": "Rockin' Squat"},
    {"spotify_id": "2wadI8Occyuywvkq9rbbn7", "name": "Verso"},
    {"spotify_id": "36XgiYYO6GEPEJybfz5vWW", "name": "Kohndo"},
    {"spotify_id": "4fshEJAfGrhkxuTamxEImN", "name": "Le Règlement"},
    {"spotify_id": "4RcwA5uQBIbcFeUNjXXytf", "name": "Fiji God"},
    {"spotify_id": "4jZA2jnUB8cz6EgOto9sMS", "name": "Yes Mccan"},
    {"spotify_id": "3DgnSCFY1j9wRW5Ujlk6iW", "name": "I.n.c.h"},
    {"spotify_id": "3fzSQmdffYb5EAzz30qUp8", "name": "LaF"},
    {"spotify_id": "3WERUo1M9Vgnk6e9rAPmaX", "name": "Meel B"},
    {"spotify_id": "0f3nk34zGWkrqKSfwE15Yd", "name": "Lady Laistee"},
    {"spotify_id": "4A1hhXvs2jAyUgsjjf1Lrj", "name": "Taipan"},
    {"spotify_id": "41J6Z8WYUSGJFn8TLEFBAD", "name": "D.A.V"},
    {"spotify_id": "1APZxUHYrPQgBNkbUjtDbr", "name": "a2z"},
    {"spotify_id": "31kG0JypoJkfxkNJAzVOEr", "name": "Despo Rutti"},
    {"spotify_id": "3lIdCDTUlgnwnoFxzvJXWH", "name": "PIHPOH"},
    {"spotify_id": "4pIlSs2li5kl1x89fYslAO", "name": "George Ka"},
    {"spotify_id": "7BZ5xQ5f3seQRI2fTpgCIT", "name": "Nino B"},
    {"spotify_id": "2muYmO0gurO8rH82MSA2Fs", "name": "Miklo"},
    {"spotify_id": "1pEt1OXsQQu9fywVAIijps", "name": "Vin-G & Fresh"},
    {"spotify_id": "7BJ85Mpgbt7ISbOt3jDlOY", "name": "La Race Canine"},
    {"spotify_id": "5fRri7qy8LZBoywvV7KwV1", "name": "40000 Gang"},
]


def seed() -> None:
    client = get_client()
    result = (
        client.table("artists")
        .upsert(SEED_ARTISTS, on_conflict="spotify_id")
        .execute()
    )
    print(f"Seeded {len(result.data)} artists:")
    for row in sorted(result.data, key=lambda r: r["name"]):
        print(f"  {row['name']}")


if __name__ == "__main__":
    seed()
